// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Appointment {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    doctor: string;
    notes?: string;
    datetime: Date;
    location?: string;
    street?: string;
    patient?: { data: User };
  };
}
export interface Appointment_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  doctor: string;
  notes?: string;
  datetime: Date;
  location?: string;
  street?: string;
  patient?: User_Plain;
}

export interface Appointment_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  doctor: string;
  notes?: string;
  datetime: Date;
  location?: string;
  street?: string;
  patient?: number;
}

export interface Appointment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  doctor: string;
  notes?: string;
  datetime: Date;
  location?: string;
  street?: string;
  patient?: AdminPanelRelationPropertyModification<User_Plain>;
}
