// Interface automatically generated by schemas-to-ts

export interface Appointment {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    doctor: string;
    active: boolean;
    notes?: string;
    datetime: Date;
  };
}
export interface Appointment_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  doctor: string;
  active: boolean;
  notes?: string;
  datetime: Date;
}

export interface Appointment_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  doctor: string;
  active: boolean;
  notes?: string;
  datetime: Date;
}

export interface Appointment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  doctor: string;
  active: boolean;
  notes?: string;
  datetime: Date;
}
