// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Meal {
  Independently = 'independently',
  Before = 'before',
  After = 'after',}

export interface Medication {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    meal: Meal;
    time: Date;
    patient?: { data: User };
  };
}
export interface Medication_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  meal: Meal;
  time: Date;
  patient?: User_Plain;
}

export interface Medication_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  meal: Meal;
  time: Date;
  patient?: number;
}

export interface Medication_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  meal: Meal;
  time: Date;
  patient?: AdminPanelRelationPropertyModification<User_Plain>;
}
